# Generated by Django 3.2.9 on 2021-12-09 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotChat',
            fields=[
                ('telegram_chat_id', models.CharField(max_length=20, verbose_name='telegram chat id')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.customuser')),
            ],
            options={
                'verbose_name': 'telegram bot chat',
                'verbose_name_plural': 'telegram bot chats',
                'ordering': ['user'],
            },
        ),
    ]
